
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Software/CLion 2023.3.1/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic - 1 - 
      The host system is: Windows - 10.0.22631 - AMD64
...
